# Generated by Django 6.0.1 on 2026-01-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('requester', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
