version: "3.9"

services:
  traefik:
    image: traefik:v3.6.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build: ./Backend-API
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_NAME: ${DBNAME}
      DB_USER: ${DBUSER}
      DB_PASSWORD: ${DBPASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SUPERUSER_USERNAME: ${DJANGOUSER}
      DJANGO_SUPERUSER_EMAIL: ${DJANGOEMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGOPASSWORD}
      DOMAIN: ${DOMAIN}
    labels:
      - "traefik.enable=true"
      # Backend only handles API + Admin
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.priority=100"
      - "traefik.docker.network=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - internal
      - web

  frontend:
    build: ./Frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      
      # Catch everything else
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    name: web
  internal: