# Generated by Django 6.0.1 on 2026-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
