# Generated by Django 4.2.4 on 2023-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INinjaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiURL', models.CharField(max_length=60)),
                ('apiKey', models.CharField(max_length=70)),
            ],
        ),
    ]
