# Generated by Django 4.2.4 on 2023-08-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_ininjasettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INinjaSettings',
            new_name='INinjaSetting',
        ),
    ]
