# Generated by Django 4.2.4 on 2023-09-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_ininjasettings_ininjasetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('postalCode', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
