# Generated by Django 4.2.4 on 2023-09-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_location_contactname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='contactName',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postalCode',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
