# Generated by Django 4.2.4 on 2023-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('bookingId', models.CharField(max_length=10)),
                ('clientId', models.CharField(max_length=20)),
                ('locationId', models.IntegerField()),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('buildupReadyTime', models.TimeField()),
                ('guests', models.IntegerField()),
                ('sound', models.BooleanField()),
                ('light', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
