# Generated by Django 4.2.4 on 2023-09-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='bookingId',
            field=models.CharField(default='', max_length=10),
        ),
    ]
