# Generated by Django 4.2.4 on 2023-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_gig_bookingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=75)),
                ('fixedPrice', models.BooleanField()),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='locationId',
            new_name='location_id',
        ),
    ]
