# Generated by Django 4.2.4 on 2023-10-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_pricesetting_rename_locationid_gig_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='location_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.location'),
        ),
    ]
