# Generated by Django 4.2.4 on 2023-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_location_id_gig_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
