# Generated by Django 4.2.4 on 2023-12-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_gig_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.location'),
        ),
    ]
