# Generated by Django 4.2.4 on 2024-01-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_gig_location_alter_gig_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('emailAddress', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('postalCode', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('paid', models.FloatField()),
                ('total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.client')),
                ('lines', models.ManyToManyField(to='API.invoicequoteline')),
            ],
        ),
        migrations.DeleteModel(
            name='INinjaSetting',
        ),
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.location'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.gigstatus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lines',
            field=models.ManyToManyField(to='API.invoicequoteline'),
        ),
    ]
