# Generated by Django 4.2.4 on 2023-12-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_gig_location_alter_gig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='invoiceIds',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gig',
            name='quoteIds',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.location'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.gigstatus'),
        ),
    ]
